version: 2

jobs:
  build:
    docker:
      - image: travisci/node:8

    steps:
      - checkout

      - run: npm install
      # CircleCI needs global installs to be sudo

      - run: sudo npm install --global apollo

      # Start the GraphQL server.  If a different command is used to
      # start the server, use it in place of `npm start` here.
      - run:
          name: Starting server
          command: npm start
          background: true

      # make sure the server has enough time to start up before running
      # commands against it
      - run: sleep 5

      # When running on the 'master' branch, push the latest version
      # of the schema to Apollo Graph Manager.
      - run: |

          if [ $TRAVIS_BRANCH == "master" ]; then
            apollo service:push --tag=master
          fi
