version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8

    steps:
      - checkout

      - run: npm install

      # When running on the 'master' branch, push the latest version
      # of the schema to Apollo Graph Manager.
      - run: |

          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            npm run apollo-graph
          fi
