version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8

    steps:
      - checkout

      - run: npm install
      # CircleCI needs global installs to be sudo

      - run: npm install --global now

      # Start the GraphQL server.  If a different command is used to
      # start the server, use it in place of `npm start` here.
      - run:
          name: Deploying on zeit
          command: now --prod -t ${NOW_TOKEN}

      # make sure the server has enough time to start up before running
      # commands against it
      - run: sleep 5

      # When running on the 'master' branch, push the latest version
      # of the schema to Apollo Graph Manager.
      - run: |

          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            npm run apollo-graph
          fi
